# -*- coding: utf-8 -*-
"""snowprogpt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177VFB3XPq8xiy4p4OTTUzP_ebpnxwG4q
"""

!pip install -q langchain pypdf faiss-cpu sentence-transformers gradio huggingface-hub

from google.colab import files
uploaded = files.upload()
pdf_path = next(iter(uploaded))

!pip install -U langchain-community langchain pypdf faiss-cpu sentence-transformers gradio huggingface-hub

!pip install -q langchain-community pypdf faiss-cpu sentence-transformers huggingface-hub gradio

from google.colab import files
from langchain_community.document_loaders import PyPDFLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_community.llms import HuggingFaceHub
from langchain.chains import RetrievalQA
import gradio as gr
import os

uploaded = files.upload()
pdf_path = next(iter(uploaded))

loader = PyPDFLoader(pdf_path)
pages = loader.load_and_split()

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)
chunks = text_splitter.split_documents(pages)

embeddings = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2",
    model_kwargs={"device": "cpu"}  # Use "cuda" if GPU is available
)

vector_db = FAISS.from_documents(chunks, embeddings)

os.environ["HUGGINGFACEHUB_API_TOKEN"] = "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" # Replace with your actual token.
llm = HuggingFaceHub(
    repo_id="google/flan-t5-large",
    model_kwargs={
        "max_length": 1000,
        "temperature": 0.3,
        "do_sample": True
    },
    task="text-generation" 
)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=vector_db.as_retriever(search_kwargs={"k": 3}) 
)

def ask_question(question):
    try:
        return qa_chain.run(question)
    except Exception as e:
        return f"Error: {str(e)}"

gr.Interface(
    fn=ask_question,
    inputs="text",
    outputs="text",
    title="PDF Chatbot",
    description="Ask questions about your uploaded PDF"
).launch(share=True)
